services:
  app:
    build: .
    container_name: instasave_app
    volumes:
      - ./app:/app/app
      - ./media:/app/media
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
